---
- name: Install package groups
  package:
    name: "{{ package_groups }}"
    state: present
  notify:
    - Install package groups optional packages

- name: Install common packages
  package:
    name:
      - acpid
      - elfutils-libelf-devel
      - podman-docker
      - dnf-utils
    state: present

- name: Install epel-release repos
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: Install more common packages
  package:
    name:
      - ethstatus
      - figlet
      - fio
      - htop
      - httping
      - iftop
      - iptraf
      - jq
      - screen
      - telnet
      - dnf-utils
      - nvme-cli
      - parallel
    state: present

- name: Install common python packages
  pip:
    name:
      - awscli
      - ansible-lint
      - glances[cpuinfo,gpu]
    state: present
