---
- name: Install package groups
  package:
    name: "{{ package_groups }}"
    state: present
  notify:
    - Install package groups optional packages

- name: Install common packages
  package:
    name:
      - acpid
      - dnf-utils
      - elfutils-libelf-devel
      - podman-docker
    state: present

- name: Install common repositories
  package:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
    state: present

- name: Install more common packages
  package:
    name:
      - dnf-utils
      #- ethstatus
      - figlet
      - fio
      - fuse-exfat
      - gnome-tweaks
      - htop
      #- httping
      - iftop
      - ImageMagick
      - iptraf
      - jq
      - librsync-devel
      - ncdu
      - ntfs-3g
      - nvme-cli
      - p7zip
      #- parallel
      - pv
      - screen
      - telnet
      - unrar
      - whois
    state: present

- name: Install common python packages
  pip:
    name:
      - ansible-lint
      - awscli
      - boto
      - docker
      - fasteners
      - glances[cpuinfo,gpu]
      - molecule
      - pynvml
    state: present
