---
- name: Install cuda reppo
  command: dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
  args:
    creates: /etc/yum.repos.d/cuda-rhel8.repo

- name: Install dkms package
  package:
    name: dkms
    state: present

- name: Install cuda package
  package:
    name: cuda
    state: present
