---
- name: Install fedora-release reppo
  yum:
    name: https://extras.getpagespeed.com/release-el8-latest.rpm
    state: present

- name: Install vlc package
  shell: shopt -s expand_aliases && source /etc/profile.d/dnfplus.sh && dnfplus install vlc
  args:
    executable: /bin/bash
