---
- name: Install common packages
  yum:
    name:
      - git
      - gcc
    state: present

- name: Disable PackageKit and ensure it is masked
  systemd:
    name: packagekit
    state: stopped
    enabled: no
    masked: yes
