---
- name: Install package groups
  package:
    name: "{{ package_groups }}"
    state: present
  notify:
    - Install package groups optional packages

- name: Install common python packages
  pip:
    name:
      - awscli
      - glances[cpuinfo]
    state: present

- name: Disable PackageKit and ensure it is masked
  systemd:
    name: packagekit
    state: stopped
    enabled: no
    masked: yes
