---
- name: Add tao repository
  yum_repository:
    name: tao
    description: Tailored Access Operations - x86_64
    file: tao
    baseurl: http://rpm.tao.s3-website-us-east-1.amazonaws.com/epel/$releasever/Everything/$basearch
    enabled: yes
    gpgcheck: no

- name: Install packages
  package:
    name:
      - dmraid
      #- duplicity
      - filezilla
      #- kdiff3
      - nomachine
      - s3cmd
      - sha3sum
      - stress
      - terminator
      - viber
      - vlc
    state: present

- name: Disable NoMachine password authentication
  lineinfile:
    path: /usr/NX/etc/server.cfg
    regexp: '^EnablePasswordDB.*$'
    line: EnablePasswordDB 1
  notify: Restart service nxserver

- name: Disable NoMachine automatic check for updates
  lineinfile:
    path: /usr/NX/etc/server.cfg
    regexp: '^UpdateFrequency.*$'
    insertafter: '^#UpdateFrequency.*$'
    line: UpdateFrequency 0
  notify: Restart service nxserver

- name: Add Viber AdBlock mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK Viber AdBlock"
    block: |
      127.0.0.1 ads.viber.com
      127.0.0.1 ads.aws.viber.com
      127.0.0.1 ads-d.viber.com
      127.0.0.1 s-bid.rmp.rakuten.com
  when: not containerized
