---
- name: Add tao repository
  yum_repository:
    name: tao
    description: Tailored Access Operations - x86_64
    file: tao
    baseurl: http://rpm.tao.s3-website-us-east-1.amazonaws.com/epel/$releasever/Everything/$basearch
    enabled: yes
    gpgcheck: no

- name: Install packages
  package:
    name:
      - vlc
      - nomachine
      - stress
      - dmraid
      #- kdiff3
      - terminator
      - filezilla
    state: present

- name: Disable NoMachine password authentication
  lineinfile:
    path: /usr/NX/etc/server.cfg
    regexp: '^EnablePasswordDB.*$'
    line: EnablePasswordDB 1
  notify: Restart service nxserver
