---
- name: Install rpmfusion-free reppo
  yum:
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
    state: present

- name: Install vlc package
  package:
    name: vlc
    state: present
