---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-centos:8}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        containerized: yes
verifier:
  name: testinfra
  lint:
    name: flake8
