#!/bin/bash -exo pipefail

pip3 install --upgrade ansible
/usr/local/bin/ansible-galaxy install vincentclee.rhel_workstation --force
/usr/local/bin/ansible-playbook ~/.ansible/roles/vincentclee.rhel_workstation/playbook.yml
